[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[100]
type=endpoint
context=internal
disallow=all
allow=alaw,ulaw
auth=auth100
aors=100

[auth100]
type=auth
auth_type=userpass
password=secret100
username=100

[100]
type=aor
max_contacts=1

[200]
type=endpoint
context=internal
disallow=all
allow=alaw,ulaw
auth=auth200
aors=200

[auth200]
type=auth
auth_type=userpass
password=secret200
username=200

[200]
type=aor
max_contacts=1