options {
    directory "/var/cache/bind";
    listen-on { any; };
    allow-query { any; };
    recursion yes;
    forwarders {
        120.0.100.1;
    };
    forward only;
    dnssec-validation no;
};

zone "entreprise.lab" IN {
    type master;
    file "/etc/bind/db.entreprise.lab";
};
