options {
    directory "/var/cache/bind";
    listen-on { any; };
    allow-query { any; };
    recursion yes;
    dnssec-validation no;
    forwarders { 120.0.100.1; };
    forward first;
};

zone "entreprise.lab" IN {
    type master;
    file "/etc/bind/db.entreprise.lab";
};
