options {
    directory "/var/cache/bind";
    listen-on { any; };
    allow-query { any; };
    recursion yes;
    dnssec-validation auto;
};

zone "entreprise.lab" IN {
    type master;
    file "/etc/bind/db.entreprise.lab";
};