FROM alpine-base:local
RUN apk add --no-cache baresip \
    --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/ \
    --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main/ \
    --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community/
